### ISSUE TITLE
User can see prompt for current letter.

### ISSUE THREAD

**Issue by kevinhyder** [kevinhyder/typing-test#3]
# Motivation
Allows the user to know precisely where their place is within the exercise.

# Task List

- [x] Select first character from each new span.
- [x] Apply CSS styling rules to make it stand out from all other additional letters (color changes from grey to black).

**Comment by victormejia** [comment]
`Add effect to cursor to designate current place` is the end result, but what are the tasks needed to accomplish this?

**Comment by kevinhyder** [comment]
![screen shot 2017-06-12 at 10 47 56 am](https://user-images.githubusercontent.com/29046239/27047420-e889218c-4f5c-11e7-8cd4-aa7e06a55b70.png)

**Comment by kevinhyder** [comment]
![screen shot 2017-06-12 at 10 51 18 am](https://user-images.githubusercontent.com/29046239/27047500-359a4834-4f5d-11e7-85ae-d37041e27aab.png)
